name: Setup Build Environment
description: 'Sets up the necessary tools to build a C/C++ project using CMake and Ninja'

inputs:
  os:
    required: true
    description: 'The os to setup the environment for'

runs:
  using: 'composite'
  steps:
    - name: Install VC tools
      if: contains(inputs.os, 'windows')
      shell: pwsh
      run: choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --norestart --wait --quiet"
    - name: Setup VC Tools
      if: contains(inputs.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: 2022
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
    - name: Setup Ninja
      uses: cmelchior/setup-ninja@master